### ISSUE TITLE
notice funcition failure

### ISSUE THREAD

**Issue by QieSen** [efb-middleware/notice#1]
Notice by @ funciton does not work properly after ETM upgraded to 2.2.5.dev1.

### Environment
Debian 11 & Python 3.9.2

EFB info: 
```
This is EFB Telegram Master Channel 2.2.5.dev1, running on default profile and instance, on EFB 2.1.1.
1 slave channel activated:
- 💬 WeChat Slave (blueset.wechat, 2.0.6.dev2)

2 middlewares activated:
- Patch Middleware (patch.PatchMiddleware, 2.0.19)
- Notice Middleware (notice.NoticeMiddleware, 0.0.6)
```

**Comment by wolfsilver** [comment]
Can you provide some error log?

Is it normal when middlewares are disabled?

**Comment by QieSen** [comment]
> Can you provide some error log?
> 
> Is it normal when middlewares are disabled?

I ran journalctl command and found nothing error. It seems everything just fine, the tag lable function works well, but the notice function actually won't work.
